# Generated by Django 4.1.2 on 2022-10-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='order',
            name='product_name',
            field=models.ManyToManyField(to='general.specialization'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
