# Generated by Django 4.1.2 on 2022-10-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='specialization',
        ),
        migrations.AddField(
            model_name='company',
            name='specialization',
            field=models.ManyToManyField(to='general.specialization'),
        ),
    ]
