# Generated by Django 4.1.2 on 2022-10-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_remove_company_specialization_company_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('start_shift', models.DateTimeField(auto_now_add=True)),
                ('finish_shift', models.DateTimeField(auto_now_add=True)),
                ('specialization', models.ManyToManyField(to='general.specialization')),
            ],
        ),
    ]
