# Generated by Django 4.1.2 on 2022-10-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Yore Name')),
                ('time_register', models.DateTimeField(auto_now_add=True, verbose_name='Time Register_in_queue')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
