# Generated by Django 4.1.2 on 2022-10-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_serv', '0003_guest_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={},
        ),
        migrations.RemoveField(
            model_name='guest',
            name='name',
        ),
        migrations.AddField(
            model_name='guest',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='guest',
            name='service',
        ),
        migrations.AddField(
            model_name='guest',
            name='service',
            field=models.CharField(choices=[('Cash management', 'Cash management'), ('Currency exchange', 'Currency exchange'), ('New account', 'New account'), ('Deposit', 'Deposit'), ('Loan', 'Loan')], max_length=255, null=True),
        ),
    ]
