# Generated by Django 4.1.2 on 2022-10-31 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker_ser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={},
        ),
        migrations.RemoveField(
            model_name='worker',
            name='specialization',
        ),
    ]
