# Generated by Django 4.1.2 on 2022-11-01 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest_serv', '0005_remove_guest_service_guest_service'),
        ('general', '0010_alter_worker_finish_shift_alter_worker_start_shift'),
        ('worker_ser', '0002_alter_worker_options_remove_worker_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('1_Waiting', '1_Waiting'), ('2_In service', '2_In service'), ('3_Done', '3_Done')], max_length=255, null=True)),
                ('start_service', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest_serv.guest')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.worker')),
            ],
        ),
        migrations.RemoveField(
            model_name='open_to_guest',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='company',
        ),
        migrations.DeleteModel(
            name='Close_current_guest',
        ),
        migrations.DeleteModel(
            name='Open_to_guest',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
